### ISSUE TITLE
Typo `recieved`

### ISSUE THREAD

**Issue by Hazurl** [Hopson97/sabre#1]
- https://github.com/Hopson97/sabre/blob/master/include/sabre/client.h#L79
- https://github.com/Hopson97/sabre/blob/master/include/sabre/client.h#L80
- https://github.com/Hopson97/sabre/blob/master/include/sabre/client.h#L30
- https://github.com/Hopson97/sabre/blob/master/include/sabre/event.h#L65

:eyes:

**Comment by Hopson97** [comment]
Done

**Comment by Hopson97** [comment]
cheers lol
